export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_POSTS = 'GET_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST'
export const GET_COMMENTS = 'GET_COMMENTS'