export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'

export const GET_POSTS = 'GET_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const CHANGE_VOTE_POST = 'CHANGE_VOTE_POST'

export const GET_COMMENTS = 'GET_COMMENTS'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const CHANGE_VOTE_COMMENT = 'CHANGE_VOTE_COMMENT'